// import necessary modules
import { createApp } from "@deroll/app";
import { encodeFunctionData, getAddress, hexToString } from "viem";
import contractAbi from "./abi.json";

let contract_address = "";

// create the app
const app = createApp({
  url: process.env.ROLLUP_HTTP_SERVER_URL || "http://127.0.0.1:5004",
});

// handle input encoded in hex
app.addAdvanceHandler(async ({ payload }) => {
  const payloadString = hexToString(payload);
  console.log("payloadString", payloadString);
  const jsonPayload = JSON.parse(payloadString);

  if (jsonPayload.method === "set_address") { // {"method": "set_address", "address": "0x000..."}
    contract_address = getAddress(jsonPayload.address);
    console.log("contract_address", contract_address);
  } else if (jsonPayload.method === "generate_number") {
     const cartesiGeneratedNumber = jsonPayload.number * 2;
     console.log("Number generated by Cartesi Backend", cartesiGeneratedNumber);

     const callData = encodeFunctionData({
      abi: contractAbi,
      functionName: "store",
      args: [cartesiGeneratedNumber],
    });

    app.createVoucher({ destination: contract_address, payload: callData });
  }
});

// start the app
app.start().catch((e) => {
  console.error(e);
  process.exit(1);
});